FROM ghcr.io/foundry-rs/foundry:stable

RUN apk update
RUN apk add --no-cache python3 py3-pip
RUN apk add make
RUN apk add yarn --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/
